language: node_js
node_js:
  - "5.5"
  - "4.2"
jdk:
  - oraclejdk7
before_install:
  # install Neo4j locally:
  - wget dist.neo4j.org/neo4j-community-2.2.0-unix.tar.gz
  - tar -xzf neo4j-community-2.2.0-unix.tar.gz
  - sed -i.bak s/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g neo4j-community-2.2.0/conf/neo4j-server.properties
  - neo4j-community-2.2.0/bin/neo4j start
install:
  - npm install
env:
  - NEO4J_AUTH=neo4j:neo4j
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 0.11
after_script:
  "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
